# Generated by Django 5.2.1 on 2025-05-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uservideolist_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Video duration in seconds'),
        ),
        migrations.CreateModel(
            name='VideoProgressInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='app.videoprogress')),
            ],
        ),
    ]
