# Generated by Django 5.2.1 on 2025-05-25 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_video_duration_videoprogressinterval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='last_watched_position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='uservideolist',
            index=models.Index(fields=['user', 'video'], name='app_uservid_user_id_711766_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['user', 'video'], name='app_videopr_user_id_569196_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogressinterval',
            index=models.Index(fields=['progress', 'start_time', 'end_time'], name='app_videopr_progres_db7192_idx'),
        ),
    ]
